require 'trash.plugins'
require 'trash.cmp'
require 'trash.lsp'
-- require 'trash.lspsaga'
require 'trash.telescope'
require 'trash.treesitter'
require 'trash.lualine'
require 'trash.bufferline'
require 'trash.mappings'
